package com.across.internetbanking.user.service;

import com.across.internetbanking.core.util.AppConstants;
import com.across.internetbanking.core.util.UniqueID;
import com.across.internetbanking.user.repository.UserRepository;

public class UserID {
    private final UserRepository userRepository;

    public UserID(UserRepository userRepository){
        this.userRepository = userRepository;
    }

    public String generateUnique(String name) {
        int spaceIdx = name.indexOf(' ');
        String firstName = (spaceIdx == -1) ? name : name.substring(0, spaceIdx);
        firstName = firstName.toLowerCase().trim(); // Customer first name for userID.

        String userID;
        boolean isUnique;
        String rawID;
        String suffix;
        int attempt = 1;

        do { 

            // Resign process after maximum failed attempts.
            if(attempt > AppConstants.MAX_CONSECUTIVE_FAILURE){
                throw new IllegalStateException("Failed to generate User ID!");
            }

            rawID = UniqueID.get().replace("-", ""); // Raw ID generated by UniqueID.get()
            suffix = (rawID.length() > 5) ? rawID.substring(0,5) : rawID; // Validated for IndexOutOfBoundException and value is allocated to suffix
            userID = (firstName + suffix + "@across"); // userID generated, yet to be finalized for it to be unique.

            isUnique = !(userRepository.exists(userID)); // Validated from databse if userID is not already been taken.
            
            attempt++;
        } while (!isUnique);
        
        return userID;
    }
}