package com.across.internetbanking.account.service;

import com.across.internetbanking.account.repository.AccountRepository;
import com.across.internetbanking.core.util.AppConstants;
import com.across.internetbanking.core.util.UniqueID;


public class AccountNumber {

    private final AccountRepository accountRepository;

    public AccountNumber(AccountRepository accountRepository){
        this.accountRepository = accountRepository;
    }
    
    public String generate(){

        String rawID, accountNumber;
        boolean isUnique;
        int attempt = 1;

        do { 
            // Resign process after maximum failed attempts.
            if(attempt > AppConstants.MAX_CONSECUTIVE_FAILURE){
                throw new IllegalStateException("Failed to generate Account Number!");
            }

            rawID = UniqueID.get().replace("-", ""); // Raw ID generated by UniqueID.get()
            accountNumber = (rawID.length() > 5) ? rawID.substring(0,5) : rawID; // Validated for IndexOutOfBoundException and value is allocated to accountNumber
           
            isUnique = !(accountRepository.exists(accountNumber)); // Validated from database if accountNumber is already been taken.
            
            attempt++;

        } while (!isUnique);

        return accountNumber;
    }
}